# Generated by Django 3.0.2 on 2020-07-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='ユーザ')),
                ('name', models.CharField(max_length=128, verbose_name='商品')),
                ('product_num', models.CharField(blank=True, max_length=128, null=True, verbose_name='商品番号')),
                ('price', models.PositiveIntegerField(verbose_name='価格')),
                ('count', models.PositiveIntegerField(verbose_name='数量')),
                ('total_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='合計')),
            ],
        ),
    ]
