# Generated by Django 3.0.7 on 2020-07-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='buy_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='購入回数'),
        ),
    ]
