# Generated by Django 3.0.2 on 2020-08-01 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buy', '0003_buy_buy_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_history', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buy.Buy')),
            ],
        ),
    ]
