# Generated by Django 3.0.2 on 2020-07-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_num',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='商品番号'),
        ),
    ]
