# Generated by Django 3.0.2 on 2020-07-25 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buy', '0003_buy_buy_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_count', models.PositiveIntegerField(verbose_name='購入回数')),
                ('product_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy.Buy')),
            ],
        ),
    ]
