# Generated by Django 3.0.2 on 2020-07-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='buy_count',
            field=models.PositiveIntegerField(default=0, verbose_name='購入回数'),
        ),
    ]
